---
- name: Install Nginx with Custom UI
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Create custom index.html directory if it doesn't exist
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
        mode: '0755'

    - name: Create custom index.html for AAP demo
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>AAP Demo</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                color: #333;
                margin: 0;
                padding: 0;
                display: flex;
                align-items: center;
                justify-content: center;
                height: 100vh;
              }
              .container {
                text-align: center;
                background-color: white;
                padding: 40px;
                border-radius: 8px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
              }
              h1 {
                color: #cc0000;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>AAP demo install Nginx</h1>
              <p>This server was configured using Ansible Automation Platform</p>
              <p>Server: {{ ansible_hostname }}</p>
              <p>IP: {{ ansible_host }}</p>
              <p>Date: {{ ansible_date_time.iso8601 }}</p>
            </div>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
      notify: Restart nginx

    - name: Enable and start Nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

  handlers:
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
